// Auto-generated from standards/*.md files — do not edit manually
export const STANDARDS_DATA: Record<string, any> = {
  LV: {
    country: "Latvia",
    country_code: "LV",
    standard: "LBN 261-23 (Ēku iekšējās elektroinstalācijas)",
    voltage: "230V (single-phase) / 400V (three-phase)",
    frequency: "50 Hz",
    socket_type: "CEE 7/4 Schuko (Type F), 16A rated",
    room_rules: {
      kitchen: { minimum_sockets: 6, dedicated_circuits: "Oven (32A), dishwasher, refrigerator", countertop_sockets: "Minimum 4 above worktop (1000–1200 mm)", notes: "One double socket per 1.5m worktop. 600mm min from water source." },
      living_room: { minimum_sockets: 5, per_wall: "At least 1 double socket per wall", tv_wall: "3 sockets recommended", notes: "Consider floor sockets for center-room arrangements." },
      dining_room: { minimum_sockets: 3, notes: "At least 1 double socket near table area. Consider floor socket for center table." },
      bedroom: { minimum_sockets: 4, bedside: "1 double socket each side of bed (600mm height)", notes: "USB-integrated sockets recommended." },
      bathroom: { minimum_sockets: 1, shaver_socket: "1 in Zone 2 with isolation transformer", notes: "All sockets RCD protected (30mA). IP44 in Zone 2. No sockets in Zones 0/1." },
      hallway: { minimum_sockets: 2, notes: "1 near entrance, 1 per 5m length." },
      home_office: { minimum_sockets: 4, desk_area: "3 at desk level (700–900mm)", notes: "Dedicated circuit for IT equipment recommended." },
      wc: { minimum_sockets: 1, notes: "Outside wet zones." },
      utility_room: { minimum_sockets: 3, dedicated_circuits: "Washing machine, dryer", notes: "1000mm height recommended." },
      garage: { minimum_sockets: 2, notes: "IP44 rated. Consider 32A EV charging." },
      balcony: { minimum_sockets: 1, notes: "IP44, RCD protected." },
    },
    circuit_requirements: {
      standard: { breaker: "16A MCB", cable: "3×2.5 mm²", max_sockets: 10, rcd: "30mA" },
      lighting: { breaker: "10A MCB", cable: "3×1.5 mm²", max_points: 12 },
      oven: { breaker: "32A MCB", cable: "3×6 mm²" },
      washing_machine: { breaker: "16A MCB", cable: "3×2.5 mm²", dedicated: true },
    },
  },
  LT: {
    country: "Lithuania",
    country_code: "LT",
    standard: "STR 2.09.02:2005 adapted to IEC 60364",
    voltage: "230V (single-phase) / 400V (three-phase)",
    frequency: "50 Hz",
    socket_type: "CEE 7/4 Schuko (Type F), 16A rated",
    room_rules: {
      kitchen: { minimum_sockets: 6, dedicated_circuits: "Oven (32A), dishwasher, refrigerator", countertop_sockets: "Minimum 4 above worktop (1000–1200 mm)", notes: "One double socket per 1.5m worktop. 600mm min from water source." },
      living_room: { minimum_sockets: 5, per_wall: "At least 1 double socket per wall", notes: "For rooms over 20m², add 1 socket per additional 5m²." },
      dining_room: { minimum_sockets: 3, notes: "At least 1 double socket near table area. Consider floor socket for center table." },
      bedroom: { minimum_sockets: 4, bedside: "1 double socket each side", notes: "USB-integrated sockets recommended." },
      bathroom: { minimum_sockets: 1, shaver_socket: "1 in Zone 2", notes: "All sockets RCD protected (30mA). IP44 in Zone 2." },
      hallway: { minimum_sockets: 2, notes: "1 near entrance, 1 per 5m length." },
      home_office: { minimum_sockets: 4, desk_area: "3 at desk level (700–900mm)", notes: "Dedicated circuit recommended for IT." },
      wc: { minimum_sockets: 1, notes: "Outside wet zones." },
      utility_room: { minimum_sockets: 3, dedicated_circuits: "Washing machine, dryer", notes: "1000mm height." },
      garage: { minimum_sockets: 2, notes: "IP44 rated. EV charging (32A) provision." },
      balcony: { minimum_sockets: 1, notes: "IP44, RCD protected." },
    },
    circuit_requirements: {
      standard: { breaker: "16A MCB", cable: "3×2.5 mm²", max_sockets: 10, rcd: "30mA" },
      lighting: { breaker: "10A MCB", cable: "3×1.5 mm²", max_points: 12 },
      oven: { breaker: "32A MCB", cable: "3×6 mm²" },
      washing_machine: { breaker: "16A MCB", cable: "3×2.5 mm²", dedicated: true },
    },
  },
  EE: {
    country: "Estonia",
    country_code: "EE",
    standard: "EVS-HD 60364 series",
    voltage: "230V (single-phase) / 400V (three-phase)",
    frequency: "50 Hz",
    socket_type: "CEE 7/4 Schuko (Type F), 16A rated",
    room_rules: {
      kitchen: { minimum_sockets: 6, dedicated_circuits: "Oven (32A), dishwasher, refrigerator", countertop_sockets: "Minimum 4 above worktop (1000–1200 mm)", notes: "One double socket per 1.5m worktop. 600mm min from sink." },
      living_room: { minimum_sockets: 5, per_wall: "At least 1 double socket per wall", notes: "For rooms over 20m², add 1 socket per additional 5m²." },
      dining_room: { minimum_sockets: 3, notes: "At least 1 double socket near table area." },
      bedroom: { minimum_sockets: 4, bedside: "1 double socket each side", notes: "USB sockets recommended." },
      bathroom: { minimum_sockets: 1, shaver_socket: "1 in Zone 2", notes: "RCD protected (30mA). IP44 in Zone 2." },
      hallway: { minimum_sockets: 2, notes: "1 near entrance, 1 per 5m length." },
      home_office: { minimum_sockets: 4, desk_area: "3 at desk level (700–900mm)", notes: "Dedicated circuit for IT recommended." },
      wc: { minimum_sockets: 1, notes: "Outside wet zones." },
      utility_room: { minimum_sockets: 3, dedicated_circuits: "Washing machine, dryer", notes: "1000mm height." },
      garage: { minimum_sockets: 2, notes: "IP44 rated. EV charging (32A) provision." },
      balcony: { minimum_sockets: 1, notes: "IP44, RCD protected." },
    },
    circuit_requirements: {
      standard: { breaker: "16A MCB", cable: "3×2.5 mm²", max_sockets: 10, rcd: "30mA" },
      lighting: { breaker: "10A MCB", cable: "3×1.5 mm²", max_points: 12 },
      oven: { breaker: "32A MCB", cable: "3×6 mm²" },
      washing_machine: { breaker: "16A MCB", cable: "3×2.5 mm²", dedicated: true },
    },
  },
};
