/**
 * Professional A3 PDF Export for Rosette.
 *
 * Generates a multi-page PDF suitable for electricians and contractors:
 *   Page 1 — Room socket layouts (IEC 60617 symbols)
 *   Page 2 — Single-line circuit diagram (switchboard)
 *   Page 3 — Wiring plan (cable routes from DB to rooms)
 *   Page 4 — Bill of materials + standards compliance + notes
 *
 * Uses jsPDF + svg2pdf.js for client-side rendering.
 * Output: A3 landscape (420×297 mm) — standard for construction drawings.
 */

import { jsPDF } from 'jspdf';
import 'svg2pdf.js';
import type { CalculationResult, CircuitInfo, Room, SocketPlacement, WiringEntry } from './types';

// ── A3 Landscape dimensions (mm) ──
const A3_W = 420;
const A3_H = 297;
const MARGIN = 15;
const CONTENT_W = A3_W - 2 * MARGIN;
const CONTENT_H = A3_H - 2 * MARGIN;

// ── Project info for title block ──
export interface PdfProjectInfo {
  projectName?: string;
  address?: string;
  clientName?: string;
  countryCode: string;
  propertyType: string;
  standard: string;
}

interface PdfData {
  rooms: Room[];
  placements: CalculationResult;
  svgRoomLayouts: string;
  svgCircuitDiagram: string;
  svgWiringDiagram: string;
  project: PdfProjectInfo;
}

// ── Helpers ──

function parseSvgElement(svgString: string): SVGElement {
  const parser = new DOMParser();
  const doc = parser.parseFromString(svgString, 'image/svg+xml');
  return doc.documentElement as unknown as SVGElement;
}

function standardName(code: string): string {
  const map: Record<string, string> = {
    LV: 'LBN 261-23 (Latvia)',
    LT: 'STR 2.09.02:2005 (Lithuania)',
    EE: 'EVS-HD 60364 (Estonia)',
  };
  return map[code] || code;
}

function countryName(code: string): string {
  const map: Record<string, string> = { LV: 'Latvia', LT: 'Lithuania', EE: 'Estonia' };
  return map[code] || code;
}

// ── Draw page frame + title block on every page ──

function drawPageFrame(
  doc: jsPDF,
  pageNum: number,
  totalPages: number,
  pageTitle: string,
  drawingNumber: string,
  project: PdfProjectInfo,
) {
  // Border frame
  doc.setDrawColor(180);
  doc.setLineWidth(0.3);
  doc.rect(MARGIN - 2, MARGIN - 2, CONTENT_W + 4, CONTENT_H + 4);

  // Title block strip at top
  doc.setFillColor(30, 41, 59); // slate-800
  doc.rect(MARGIN, MARGIN, CONTENT_W, 14, 'F');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.setTextColor(255);
  doc.text(`⚡ rosette — ${pageTitle}`, MARGIN + 4, MARGIN + 9);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(7);
  doc.text(
    `${project.projectName || 'Electrical Installation Plan'} · ${countryName(project.countryCode)} · ${project.propertyType}`,
    MARGIN + CONTENT_W / 2,
    MARGIN + 9,
    { align: 'center' },
  );

  doc.text(`Drawing ${drawingNumber}`, MARGIN + CONTENT_W - 4, MARGIN + 5, { align: 'right' });
  doc.text(`Page ${pageNum}/${totalPages}`, MARGIN + CONTENT_W - 4, MARGIN + 11, { align: 'right' });

  // Bottom strip
  doc.setFillColor(241, 245, 249); // slate-100
  doc.rect(MARGIN, MARGIN + CONTENT_H - 8, CONTENT_W, 8, 'F');
  doc.setTextColor(107, 114, 128);
  doc.setFontSize(6);
  doc.text(
    `IEC 60617 symbols · ${standardName(project.countryCode)} · Generated by rosette (rosette.naurolabs.com) · ${new Date().toISOString().slice(0, 10)}`,
    MARGIN + CONTENT_W / 2,
    MARGIN + CONTENT_H - 3,
    { align: 'center' },
  );

  // Reset text color
  doc.setTextColor(0);
}

// ── Render SVG into PDF page ──

async function renderSvgPage(
  doc: jsPDF,
  svgString: string,
  yOffset: number,
  maxWidth: number,
  maxHeight: number,
): Promise<void> {
  const svgEl = parseSvgElement(svgString);

  // Get original SVG dimensions
  const vb = svgEl.getAttribute('viewBox')?.split(' ').map(Number) || [0, 0, 600, 400];
  const svgW = vb[2] || 600;
  const svgH = vb[3] || 400;

  // Scale to fit within max bounds, maintaining aspect ratio
  const scaleX = maxWidth / svgW;
  const scaleY = maxHeight / svgH;
  const scale = Math.min(scaleX, scaleY);

  const renderW = svgW * scale;
  const renderH = svgH * scale;

  // Center horizontally
  const xOffset = MARGIN + (CONTENT_W - renderW) / 2;

  await doc.svg(svgEl, {
    x: xOffset,
    y: yOffset,
    width: renderW,
    height: renderH,
  });
}

// ── Page 4: Bill of Materials + Standards ──

function drawMaterialsPage(doc: jsPDF, data: PdfData, pageNum: number, totalPages: number) {
  drawPageFrame(doc, pageNum, totalPages, 'Bill of Materials & Standards', 'E-04', data.project);

  const { placements, rooms, project } = data;
  const circuits: CircuitInfo[] = placements.circuits || [];
  const wiring: WiringEntry[] = placements.wiring || [];

  let y = MARGIN + 22;
  const col1 = MARGIN + 6;
  const col2 = MARGIN + CONTENT_W / 2 + 10;

  // ── Left column: Socket summary ──
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.setTextColor(30, 41, 59);
  doc.text('Socket Summary', col1, y);
  y += 6;

  // Table header
  doc.setFillColor(241, 245, 249);
  doc.rect(col1, y, CONTENT_W / 2 - 16, 6, 'F');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(7);
  doc.setTextColor(75, 85, 99);
  doc.text('Room', col1 + 2, y + 4);
  doc.text('Type', col1 + 60, y + 4);
  doc.text('Area (m²)', col1 + 100, y + 4);
  doc.text('Sockets', col1 + 140, y + 4);
  y += 7;

  doc.setFont('helvetica', 'normal');
  doc.setTextColor(17, 24, 39);
  const socketPlacements: SocketPlacement[] = placements.placements || [];
  rooms.forEach((room) => {
    const count = socketPlacements.filter((p) => p.room_id === room.id || p.room_name === room.name).length;
    doc.text(room.name || room.type, col1 + 2, y + 4);
    doc.text(room.type, col1 + 60, y + 4);
    doc.text(String(room.area_m2 || '?'), col1 + 100, y + 4);
    doc.text(String(count), col1 + 140, y + 4);
    doc.setDrawColor(229, 231, 235);
    doc.line(col1, y + 6, col1 + CONTENT_W / 2 - 16, y + 6);
    y += 7;
    if (y > MARGIN + CONTENT_H - 30) return; // safety
  });

  // Total row
  y += 2;
  doc.setFont('helvetica', 'bold');
  doc.setFillColor(79, 70, 229); // indigo
  doc.setTextColor(255);
  doc.rect(col1, y, CONTENT_W / 2 - 16, 7, 'F');
  doc.text('TOTAL', col1 + 2, y + 5);
  doc.text(`${placements.total_sockets || socketPlacements.length} sockets`, col1 + 140, y + 5);
  doc.setTextColor(0);
  y += 12;

  // ── Left column: Circuit table ──
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.setTextColor(30, 41, 59);
  doc.text('Circuit Allocation', col1, y);
  y += 6;

  doc.setFillColor(241, 245, 249);
  doc.rect(col1, y, CONTENT_W / 2 - 16, 6, 'F');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(7);
  doc.setTextColor(75, 85, 99);
  doc.text('Circuit', col1 + 2, y + 4);
  doc.text('Breaker', col1 + 40, y + 4);
  doc.text('Cable', col1 + 70, y + 4);
  doc.text('Sockets', col1 + 110, y + 4);
  doc.text('RCD Group', col1 + 140, y + 4);
  y += 7;

  doc.setFont('helvetica', 'normal');
  doc.setTextColor(17, 24, 39);
  circuits.forEach((c) => {
    if (y > MARGIN + CONTENT_H - 20) return;
    doc.text(c.id || '', col1 + 2, y + 4);
    doc.text(c.breaker || '16A', col1 + 40, y + 4);
    doc.text(c.cable || '3×2.5mm²', col1 + 70, y + 4);
    doc.text(String(c.sockets?.length || 0), col1 + 110, y + 4);
    doc.text(c.rcd_group || '', col1 + 140, y + 4);
    doc.setDrawColor(229, 231, 235);
    doc.line(col1, y + 6, col1 + CONTENT_W / 2 - 16, y + 6);
    y += 7;
  });

  // ── Right column: Cable summary ──
  let ry = MARGIN + 22;
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.setTextColor(30, 41, 59);
  doc.text('Cable Requirements', col2, ry);
  ry += 6;

  if (wiring.length > 0) {
    doc.setFillColor(241, 245, 249);
    doc.rect(col2, ry, CONTENT_W / 2 - 16, 6, 'F');
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(7);
    doc.setTextColor(75, 85, 99);
    doc.text('Route', col2 + 2, ry + 4);
    doc.text('Cable Type', col2 + 70, ry + 4);
    doc.text('Length (m)', col2 + 130, ry + 4);
    ry += 7;

    doc.setFont('helvetica', 'normal');
    doc.setTextColor(17, 24, 39);
    wiring.forEach((w) => {
      if (ry > MARGIN + CONTENT_H / 2) return;
      doc.text(`DB → ${w.to_room || w.circuit_id || '?'}`, col2 + 2, ry + 4);
      doc.text(w.cable_type || 'NYM-J 3×2.5mm²', col2 + 70, ry + 4);
      doc.text(String(w.estimated_length_m || '?'), col2 + 130, ry + 4);
      doc.setDrawColor(229, 231, 235);
      doc.line(col2, ry + 6, col2 + CONTENT_W / 2 - 16, ry + 6);
      ry += 7;
    });

    const totalCable = wiring.reduce((s: number, w) => s + (w.estimated_length_m || 0), 0);
    if (totalCable > 0) {
      ry += 2;
      doc.setFont('helvetica', 'bold');
      doc.setFillColor(16, 185, 129); // emerald
      doc.setTextColor(255);
      doc.rect(col2, ry, CONTENT_W / 2 - 16, 7, 'F');
      doc.text('TOTAL CABLE', col2 + 2, ry + 5);
      doc.text(`~${totalCable} m`, col2 + 130, ry + 5);
      doc.setTextColor(0);
      ry += 14;
    }
  } else {
    doc.setFont('helvetica', 'italic');
    doc.setFontSize(8);
    doc.setTextColor(107, 114, 128);
    doc.text('Cable routing data not available — verify lengths on-site', col2, ry + 4);
    ry += 14;
  }

  // ── Right column: Standards compliance ──
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.setTextColor(30, 41, 59);
  doc.text('Standards Compliance', col2, ry);
  ry += 7;

  const checks = [
    `Country standard: ${standardName(project.countryCode)}`,
    'Symbology: IEC 60617 (EN 60617)',
    'Installation: IEC 60364 (HD 60364)',
    'Wire colors: IEC 60446',
    'Drawing format: IEC 61082',
    `Property type: ${project.propertyType}`,
    'RCD protection: 30mA Type A on all circuits',
    'Voltage drop limit: ≤ 3%',
    `Total circuits: ${circuits.length}`,
    `Total sockets: ${placements.total_sockets || socketPlacements.length}`,
  ];

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(7.5);
  doc.setTextColor(17, 24, 39);
  checks.forEach((line) => {
    if (ry > MARGIN + CONTENT_H - 20) return;
    doc.text(`✓  ${line}`, col2 + 2, ry + 4);
    ry += 6;
  });

  // ── Notes section at bottom right ──
  ry += 8;
  if (ry < MARGIN + CONTENT_H - 40) {
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(9);
    doc.setTextColor(30, 41, 59);
    doc.text('Notes', col2, ry);
    ry += 5;
    doc.setDrawColor(200);
    doc.rect(col2, ry, CONTENT_W / 2 - 16, 30);
    doc.setFont('helvetica', 'italic');
    doc.setFontSize(6.5);
    doc.setTextColor(156, 163, 175);
    doc.text('Verify all measurements and cable lengths on-site before installation.', col2 + 3, ry + 5);
    doc.text('This plan is AI-generated and must be reviewed by a certified electrician.', col2 + 3, ry + 11);
    if (project.address) {
      doc.text(`Address: ${project.address}`, col2 + 3, ry + 17);
    }
    if (project.clientName) {
      doc.text(`Client: ${project.clientName}`, col2 + 3, ry + 23);
    }
  }
}

// ── Main export function ──

export async function exportPdf(data: PdfData): Promise<void> {
  const totalPages = 4;
  const doc = new jsPDF({
    orientation: 'landscape',
    unit: 'mm',
    format: 'a3',
  });

  // Page 1: Room layouts
  drawPageFrame(doc, 1, totalPages, 'Room Socket Layouts', 'E-01', data.project);
  if (data.svgRoomLayouts) {
    try { await renderSvgPage(doc, data.svgRoomLayouts, MARGIN + 18, CONTENT_W, CONTENT_H - 30); }
    catch (e) { console.warn('PDF: Room layouts SVG render failed', e); }
  }

  // Page 2: Circuit diagram
  doc.addPage('a3', 'landscape');
  drawPageFrame(doc, 2, totalPages, 'Single-Line Circuit Diagram', 'E-02', data.project);
  if (data.svgCircuitDiagram) {
    try { await renderSvgPage(doc, data.svgCircuitDiagram, MARGIN + 18, CONTENT_W, CONTENT_H - 30); }
    catch (e) { console.warn('PDF: Circuit diagram SVG render failed', e); }
  }

  // Page 3: Wiring plan
  doc.addPage('a3', 'landscape');
  drawPageFrame(doc, 3, totalPages, 'Wiring Plan', 'E-03', data.project);
  if (data.svgWiringDiagram) {
    try { await renderSvgPage(doc, data.svgWiringDiagram, MARGIN + 18, CONTENT_W, CONTENT_H - 30); }
    catch (e) { console.warn('PDF: Wiring plan SVG render failed', e); }
  }

  // Page 4: Bill of materials + standards
  doc.addPage('a3', 'landscape');
  drawMaterialsPage(doc, data, 4, totalPages);

  // Save
  const date = new Date().toISOString().slice(0, 10);
  const name = data.project.projectName?.replace(/\s+/g, '-').toLowerCase() || 'plan';
  doc.save(`rosette-${name}-${data.project.countryCode.toLowerCase()}-${date}.pdf`);
}
